### ISSUE TITLE
Singleton config and multiple consumer configurations

### ISSUE THREAD

**Issue by simPod** [weiboad/kafka-php#177]
As the ConsumerConfig is a singleton, how to create multiple consumers with eg. different groups?

**Comment by lcobucci** [comment]
You don't 😢 

Killing the whole singleton thing is listed in #139 but we didn't get to implement that yet... I'm working in isolating dependencies and have a better connection management right now (which IMO is the first step to exterminate the singletons) but I'm quite busy with other stuff atm that I didn't manage to finish it

**Comment by lcobucci** [comment]
What you would have to do for now is simply have each group in it's own process.

**Comment by simPod** [comment]
I'll try to look at it

**Comment by jcchavezs** [comment]
This would be a really nice improvement. I can work on this myself.

The reason for this to be important is that let's say you use kafka for event sourcing in your application but you also one to use kafka for monitoring or observability, they clearly won't share configuration (and might be probably different instances). At the moment we have to do such trick:

```
public function __construct(Producer $producer = null, array $config = null, ...)
    {
        $config = $config ?: [
            'broker_list' => '127.0.0.1:9092',
        ];

        $brokerList = ProducerConfig::getInstance()->getMetadataBrokerList();

        $kConfig = ProducerConfig::getInstance();
        $kConfig->setMetadataBrokerList($config['broker_list']);

         $this->producer = $producer ?: new Producer();
        if (!empty($brokerList)) {
            ProducerConfig::getInstance()->setMetadataBrokerList($brokerList);
        }
    }
```
(source https://github.com/jcchavezs/zipkin-php-reporter-kafka/blob/master/src/ZipkinReporterKafka/Reporter.php#L35)

I propose that we keep the global config and use it when you don't pass a config in the producer arguments, otherwise use the provided one.

**Comment by lcobucci** [comment]
@jcchavezs keeping a global config is quite a mess IHMO, ideally we should be able to have multiple producer and consumer in the same event loop and they should just work properly. This is an edge case, for sure, but solving that would remove completely the messy singleton thing we have now.

I'm still refactoring the connection management area but am doing this together with the other projects I maintain - which makes things a bit harder 😄. Give me a couple days and I'll submit a PR with my progress but if anyone wants to help it would be amazing if we could address #213 and #214!

**Comment by Sevavietl** [comment]
@lcobucci, hi. Is there any luck dropping singletons? I may be able to help you with this but need to know what is already done, so I can choose the right direction.

The real problem I have faced is the `Broker` when using producer inside the consumer. As we can specify the topics for the consumer the metadata will be fetched only for those topics, so only those topics will be available for the broker. This breaks the producer that uses the same broker as he will have access only to topics that consumer subscribed to...

**Comment by lcobucci** [comment]
@Sevavietl unfortunately I haven't been able to continue my implementation, due to a massive amount of work at my company. However I think that this situation will soon change and I will finally address this.

The main challenge here is that we need to invert the place where we control the `EventLoop` in order to be able to drop the singleton, but that is not a small change to make since the lib we're using for that controls everything using singletons.

IMHO a more appropriated solution would be replacing amp for reactphp, which always encourage people to inject the event loop. We could even drop our socket classes by the ones provided by reactphp, use promises, and a lot of cool stuff. However we must ensure that #213 and #214 are implemented and work fine before of jumping into that journey.

> The real problem I have faced is the Broker when using producer inside the consumer. As we can specify the topics for the consumer the metadata will be fetched only for those topics, so only those topics will be available for the broker. This breaks the producer that uses the same broker as he will have access only to topics that consumer subscribed to...
> 
> I've made a workaround in consumer client code, by subscribing to all topics and while consuming ignore all but the target one. But this is bad voodoo)

Ouch! I'm really sorry for this 😢

**Comment by Sevavietl** [comment]
@lcobucci, no worries -- have the same thing with work too)

Regarding `EventLoop`, well, I think it is ok that `amp` uses a singleton for the loop, as there can be only one event loop. We actually using `amp` for the whole app, so global loop comes handy because we were able to integrate this library without much pain using `Loop::defer` in the callback of the consumer.

It is a real problem that the `Broker` and `Config` are singletons. I conclude this from the situation above where topics for producer and consumer became dependant on one another.

I would be glad to help with what I can (and this is actually in my interests because we use this library takes a crucial part in my app, such as providing communication, so it is not without ulterior motives:))
